version: '2'
services:
    web:
      container_name: web
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - "sql"
      ports:
         - "8000:8000"

    sql:
        image: microsoft/mssql-server-2016-express-windows
        container_name: sql
        ports:
         - "1433:1433"
        environment:
         - sa_password=P@ssw0rd

networks:
  default:
    external:
      name: nat